export type ThemeClass = 
{
    class: string, 
    pressed?: string
}
export type Theme = 
{
    name: string,
    "0": ThemeClass,
    "1": ThemeClass,
    "2": ThemeClass,
    "3": ThemeClass,
    "4": ThemeClass,
    "5": ThemeClass,
    "6": ThemeClass,
    "7": ThemeClass,
    "8": ThemeClass,
    "9": ThemeClass,
    ".": ThemeClass,
    "AC": ThemeClass,
    "+": ThemeClass,
    "-": ThemeClass,
    "*": ThemeClass,
    "/": ThemeClass,
    "=": ThemeClass,
    "%": ThemeClass,
    "+/-": ThemeClass,
    "display": ThemeClass,
    "current-input": ThemeClass,
    "old-input": ThemeClass,
    "grid-buttons": ThemeClass,
    "calculator": ThemeClass,
}

export const Themes: Theme[] = 
[
    {
        name: "Standard Blue",
        "0": {class: "SB_btn-secondary aspect-auto col-span-2", pressed: "bg-slate-300/20" },
        "1": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "2": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "3": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "4": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "5": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "6": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "7": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "8": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "9": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        ".": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "AC": {class: "SB_btn-secondary", pressed: "bg-slate-300/20"},
        "+": {class: "SB_btn-primary", pressed: "bg-slate-300/30"},
        "-": {class: "SB_btn-primary", pressed: "bg-slate-300/30"},
        "*": {class: "SB_btn-primary", pressed: "bg-slate-300/30"},
        "/": {class: "SB_btn-primary", pressed: "bg-slate-300/30"},
        "=": {class: "SB_btn-primary", pressed: "bg-slate-300/30"},
        "%": {class: "SB_btn-secondary"},
        "+/-": {class: "SB_btn-secondary"},
        "display": {class: "SB_display"},
        "current-input": {class: "SB_current-input"},
        "old-input": {class: "SB_old-input"},
        "grid-buttons": {class: "SB_grid-buttons"},
        "calculator": {class: "SB_calculator"},
    },
    {
        name: "Standard Red",
        "0": {class: "SR_btn-secondary aspect-auto col-span-2", pressed: "bg-slate-300/20" },
        "1": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "2": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "3": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "4": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "5": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "6": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "7": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "8": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "9": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        ".": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "AC": {class: "SR_btn-secondary", pressed: "bg-slate-300/20"},
        "+": {class: "SR_btn-primary", pressed: "bg-slate-300/30"},
        "-": {class: "SR_btn-primary", pressed: "bg-slate-300/30"},
        "*": {class: "SR_btn-primary", pressed: "bg-slate-300/30"},
        "/": {class: "SR_btn-primary", pressed: "bg-slate-300/30"},
        "=": {class: "SR_btn-primary", pressed: "bg-slate-300/30"},
        "%": {class: "SR_btn-secondary"},
        "+/-": {class: "SR_btn-secondary"},
        "display": {class: "SR_display"},
        "current-input": {class: "SR_current-input"},
        "old-input": {class: "SR_old-input"},
        "grid-buttons": {class: "SR_grid-buttons"},
        "calculator": {class: "SR_calculator"},
    },
    {
        name: "Standard Green",
        "0": {class: "SG_btn-secondary aspect-auto col-span-2", pressed: "bg-slate-300/20" },
        "1": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "2": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "3": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "4": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "5": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "6": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "7": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "8": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "9": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        ".": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "AC": {class: "SG_btn-secondary", pressed: "bg-slate-300/20"},
        "+": {class: "SG_btn-primary", pressed: "bg-slate-300/30"},
        "-": {class: "SG_btn-primary", pressed: "bg-slate-300/30"},
        "*": {class: "SG_btn-primary", pressed: "bg-slate-300/30"},
        "/": {class: "SG_btn-primary", pressed: "bg-slate-300/30"},
        "=": {class: "SG_btn-primary", pressed: "bg-slate-300/30"},
        "%": {class: "SG_btn-secondary"},
        "+/-": {class: "SG_btn-secondary"},
        "display": {class: "SG_display"},
        "current-input": {class: "SG_current-input"},
        "old-input": {class: "SG_old-input"},
        "grid-buttons": {class: "SG_grid-buttons"},
        "calculator": {class: "SG_calculator"},
    },
    {
        name: "Iphone Theme",
        "0": {class: "IT_btn-first-type aspect-auto col-span-2", pressed: "bg-zinc-800" },
        "1": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        "2": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        "3": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        "4": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        "5": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        "6": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        "7": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        "8": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        "9": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        ".": {class: "IT_btn-first-type", pressed: "bg-zinc-800"},
        "AC": {class: "IT_btn-second-type", pressed: "bg-zinc-500"},
        "+": {class: "IT_btn-third-type", pressed: "bg-amber-600"},
        "-": {class: "IT_btn-third-type", pressed: "bg-amber-600"},
        "*": {class: "IT_btn-third-type", pressed: "bg-amber-600"},
        "/": {class: "IT_btn-third-type", pressed: "bg-amber-600"},
        "=": {class: "IT_btn-third-type", pressed: "bg-amber-600"},
        "%": {class: "IT_btn-second-type"},
        "+/-": {class: "IT_btn-second-type"},
        "display": {class: "IT_display"},
        "current-input": {class: "IT_current-input"},
        "old-input": {class: "IT_old-input"},
        "grid-buttons": {class: "IT_grid-buttons"},
        "calculator": {class: "IT_calculator"},
    },
    {
        name: "Purple Laguna",
        "0": {class: "PL_btn-first-type row-start-5 row-end-6 col-start-2 col-end-3", pressed: "bg-gray-300" },
        "1": {class: "PL_btn-first-type row-start-4 row-end-5 col-start-1 col-end-2", pressed: "bg-gray-300"},
        "2": {class: "PL_btn-first-type row-start-4 row-end-5 col-start-2 col-end-3", pressed: "bg-gray-300"},
        "3": {class: "PL_btn-first-type row-start-4 row-end-5 col-start-3 col-end-4", pressed: "bg-gray-300"},
        "4": {class: "PL_btn-first-type row-start-3 row-end-4 col-start-1 col-end-2", pressed: "bg-gray-300"},
        "5": {class: "PL_btn-first-type row-start-3 row-end-4 col-start-2 col-end-3", pressed: "bg-gray-300"},
        "6": {class: "PL_btn-first-type row-start-3 row-end-4 col-start-3 col-end-4", pressed: "bg-gray-300"},
        "7": {class: "PL_btn-first-type row-start-2 row-end-3 col-start-1 col-end-2", pressed: "bg-gray-300"},
        "8": {class: "PL_btn-first-type row-start-2 row-end-3 col-start-2 col-end-3", pressed: "bg-gray-300"},
        "9": {class: "PL_btn-first-type row-start-2 row-end-3 col-start-3 col-end-4", pressed: "bg-gray-300"},
        ".": {class: "PL_btn-first-type row-start-5 row-end-6 col-start-3 col-end-4", pressed: "bg-gray-300"},
        "AC": {class: "PL_btn-second-type row-start-1 row-end-2 col-start-1 col-end-2", pressed: "bg-gray-300"},
        "+": {class: "PL_btn-second-type row-start-3 row-end-4 col-start-4 col-end-5", pressed: "bg-gray-300"},
        "-": {class: "PL_btn-second-type row-start-2 row-end-3 col-start-4 col-end-5", pressed: "bg-gray-300"},
        "*": {class: "PL_btn-second-type row-start-1 row-end-2 col-start-3 col-end-4", pressed: "bg-gray-300"},
        "/": {class: "PL_btn-second-type row-start-1 row-end-2 col-start-2 col-end-3", pressed: "bg-gray-300"},
        "=": {class: "PL_btn-third-type aspect-auto row-start-4 row-end-6 col-start-4 col-end-5", pressed: "bg-violet-700"},
        "%": {class: "PL_btn-first-type row-start-5 row-end-6 col-start-1 col-end-2"},
        "+/-": {class: "PL_btn-second-type row-start-1 row-end-2 col-start-4 col-end-5"},
        "display": {class: "PL_display"},
        "current-input": {class: "PL_current-input"},
        "old-input": {class: "PL_old-input"},
        "grid-buttons": {class: "PL_grid-buttons"},
        "calculator": {class: "PL_calculator"},
    },
    {
        name: "Dark Laguna",
        "0": {class: "DL_btn-first-type row-start-5 row-end-6 col-start-2 col-end-3", pressed: "bg-gray-300" },
        "1": {class: "DL_btn-first-type row-start-4 row-end-5 col-start-1 col-end-2", pressed: "bg-gray-300"},
        "2": {class: "DL_btn-first-type row-start-4 row-end-5 col-start-2 col-end-3", pressed: "bg-gray-300"},
        "3": {class: "DL_btn-first-type row-start-4 row-end-5 col-start-3 col-end-4", pressed: "bg-gray-300"},
        "4": {class: "DL_btn-first-type row-start-3 row-end-4 col-start-1 col-end-2", pressed: "bg-gray-300"},
        "5": {class: "DL_btn-first-type row-start-3 row-end-4 col-start-2 col-end-3", pressed: "bg-gray-300"},
        "6": {class: "DL_btn-first-type row-start-3 row-end-4 col-start-3 col-end-4", pressed: "bg-gray-300"},
        "7": {class: "DL_btn-first-type row-start-2 row-end-3 col-start-1 col-end-2", pressed: "bg-gray-300"},
        "8": {class: "DL_btn-first-type row-start-2 row-end-3 col-start-2 col-end-3", pressed: "bg-gray-300"},
        "9": {class: "DL_btn-first-type row-start-2 row-end-3 col-start-3 col-end-4", pressed: "bg-gray-300"},
        ".": {class: "DL_btn-first-type row-start-5 row-end-6 col-start-3 col-end-4", pressed: "bg-gray-300"},
        "AC": {class: "DL_btn-second-type row-start-1 row-end-2 col-start-1 col-end-2", pressed: "bg-gray-300"},
        "+": {class: "DL_btn-second-type row-start-3 row-end-4 col-start-4 col-end-5", pressed: "bg-gray-300"},
        "-": {class: "DL_btn-second-type row-start-2 row-end-3 col-start-4 col-end-5", pressed: "bg-gray-300"},
        "*": {class: "DL_btn-second-type row-start-1 row-end-2 col-start-3 col-end-4", pressed: "bg-gray-300"},
        "/": {class: "DL_btn-second-type row-start-1 row-end-2 col-start-2 col-end-3", pressed: "bg-gray-300"},
        "=": {class: "DL_btn-third-type aspect-auto row-start-4 row-end-6 col-start-4 col-end-5", pressed: "bg-zinc-900"},
        "%": {class: "DL_btn-first-type row-start-5 row-end-6 col-start-1 col-end-2"},
        "+/-": {class: "DL_btn-second-type row-start-1 row-end-2 col-start-4 col-end-5"},
        "display": {class: "DL_display"},
        "current-input": {class: "DL_current-input"},
        "old-input": {class: "DL_old-input"},
        "grid-buttons": {class: "DL_grid-buttons"},
        "calculator": {class: "DL_calculator"},
    },
];